In [1]:
#Write a python program to recognize the number 0, 1, 2, 39. A 5 * 3 matrix forms the numbers. For any valid point it is taken as 1 and invalid point it is taken as 0. The net has to be trained to recognize all the numbers and when the test data is given, the network has to recognize the particular numbers

In [6]:
import numpy as np
from sklearn.neural_network import MLPClassifier

# Define training data for numbers 0, 1, 2, and 39
X_train = np.array([
    [1, 1, 1, 1, 1,   # 0
     1, 0, 0, 0, 1,
     1, 0, 0, 0, 1],
    
    [0, 0, 1, 0, 0,   # 1
     0, 0, 1, 0, 0,
     0, 0, 1, 0, 0],
    
    [1, 1, 1, 0, 0,   # 2
     1, 1, 1, 0, 0,
     1, 1, 1, 0, 0],
    
    [1, 1, 1, 0, 0,   # 39
     1, 1, 1, 0, 0,
     1, 1, 1, 0, 0]
])

# Flatten the 5x3 matrices to 1D arrays
X_train = X_train.reshape(X_train.shape[0], -1)

# Define labels for the training data
y_train = np.array([0, 1, 2, 39])

# Define test data
X_test = np.array([
    [1, 1, 1, 1, 1,   # 0
     1, 0, 0, 0, 1,
     1, 0, 0, 0, 1],
    
    [0, 0, 1, 0, 0,   # 1
     0, 0, 1, 0, 0,
     0, 0, 1, 0, 0],
    
    [1, 1, 1, 0, 0,   # 2
     1, 1, 1, 0, 0,
     1, 1, 1, 0, 0],
    
    [1, 1, 1, 0, 0,   # 39
     1, 1, 1, 0, 0,
     1, 1, 1, 0, 0]
])

# Flatten the test data
X_test = X_test.reshape(X_test.shape[0], -1)

# Create and train the MLP classifier
clf = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=1)
clf.fit(X_train, y_train)

# Predict the labels for the test data
predicted_labels = clf.predict(X_test)

print("Test Data:")
print(X_test.reshape(-1, 5, 3))  # Reshape back to 5x3 matrices for better readability
print("\nPredicted Labels:")
print(predicted_labels)


Test Data:
[[[1 1 1]
  [1 1 1]
  [0 0 0]
  [1 1 0]
  [0 0 1]]

 [[0 0 1]
  [0 0 0]
  [0 1 0]
  [0 0 0]
  [1 0 0]]

 [[1 1 1]
  [0 0 1]
  [1 1 0]
  [0 1 1]
  [1 0 0]]

 [[1 1 1]
  [0 0 1]
  [1 1 0]
  [0 1 1]
  [1 0 0]]]

Predicted Labels:
[ 0  1 39 39]
